Feat/maquetar slider inicial
Open-Bootcamp/productos-km0 pull request #41
Opened 2022-08-12 21:28 UTC by JTuyuc7

Maquetacion del splash scree, mostrar sliders y validar que se muestren solo una vez.

2022-08-15 08:20 UTC, pedrovelasquez9 commented
@JTuyuc7 la PR está apuntando a main, recuerden que toda funcionalidad desarrollada debe ir a develop, de momento, edita la PR para apuntar a develop

2022-08-15 08:21 UTC, pedrovelasquez9 commented on productos-KM0-app/src/screens/Sliders.js
> +            console.log('Navegar a iniciar sesion, y cerrar el onboarding')
Evitemos tener console.logs al subir el código al repo

2022-08-15 08:23 UTC, pedrovelasquez9 requested changes
Revisar el comentario del console log, evitemos tenerlos al subir código al repo

2022-08-15 16:24 UTC, JTuyuc7 commented on productos-KM0-app/src/screens/Sliders.js
> +            console.log('Navegar a iniciar sesion, y cerrar el onboarding')
@pedrovelasquez9 Cambios hechos, rama ahora apunta a dev, console.logs removidos.

2022-08-16 13:10 UTC, pedrovelasquez9 commented
@JTuyuc7 la PR indica la existencia de un conflicto con el package.json de dev, actualiza la PR tras solventar el conflicto para poder realizar el merge

2022-08-20 04:51 UTC, closed without merging