Registro usuario
Open-Bootcamp/productos-km0 pull request #43
Opened 2022-08-15 22:42 UTC by GermanCuevas

Se crean las vistas de formularios : productor y comprador.
Se usa formik y yup para la valdacion de los formularios.

2022-08-16 13:08 UTC, pedrovelasquez9 requested changes
La PR indica un conflicto de archivos, actualiza la PR con los conflictos solucionados para poder hacer el merge

2022-08-17 03:39 UTC, GermanCuevas commented
Se actualiza el package.json y se remueve el yarn.lock para no tener conflictos.

2022-08-17 04:00 UTC, GermanCuevas reviewed
Se borra archivo yarn.lock

2022-08-17 09:37 UTC, heyanabanana commented
La pr sigue teniendo conflictos con la rama base, arregladlo para poder aceptarla.

2022-08-17 20:04 UTC, GermanCuevas commented
Se siguen los pasos para resolucion de conflictos.

git rebase dev
Se resuelven los conflictos de forma manual.

git add package.json

git rebase --continue

Se borra archivo yarn.lock
git add yarn.lock
git rebase --continue

:q

Se repite la operacion hasta actualizar de forma correcta el package.json.

La terminal solicita un : git pull y luego un git push.
Se colocan los comandos y se autogenera el ultimo commit 'Merge branch ... '(81f6c2c)

2022-08-21 00:18 UTC, merged